apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup-workspace
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/output/*
